Controllers/CampusController.cs
using Microsoft.AspNetCore.Mvc;
using Report_a_Fault.Interface;
using Report_a_Fault.Models;

namespace Report_a_Fault.Controllers
{
    public class CampusController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CampusController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            var campuses = _unitOfWork.Campus.GetAll();

            return View(campuses);
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(Campus campus)
        {
            campus.CampusId= Guid.NewGuid().ToString();
            campus.CampusName = campus.CampusName.ToUpper();
            campus.DateOpended = DateTime.Now; 
            _unitOfWork.Campus.Add(campus);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Update(string id)
        {
            var campus = _unitOfWork.Campus.Get(c => c.CampusId == id);

            return View(campus);
        }
        [HttpPost]
        public IActionResult Update(Campus campus)
        {
            campus.CampusName = campus.CampusName.ToUpper();
            _unitOfWork.Campus.Update(campus);
            _unitOfWork.Save();
           return RedirectToAction("Index");
        }
        public IActionResult Details(string id)
        {
            var campus = _unitOfWork.Campus.Get(c => c.CampusId == id);

            return View(campus);
        }
        [HttpGet]
        public IActionResult Delete(string id)
        {
            var campus = _unitOfWork.Campus.Get(c => c.CampusId == id);

            return View(campus);
        }
        [HttpPost]
        public IActionResult Delete(Campus campus)
        {
            var CampusFromDb = _unitOfWork.Campus.Get(u=>u.CampusId==campus.CampusId);
            _unitOfWork.Campus.Remove(CampusFromDb);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }

    }
}

Controllers/FaultController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Report_a_Fault.Interface;
using Report_a_Fault.Models;
using Report_a_Fault.ViewModel;
using System.Drawing.Printing;

namespace Report_a_Fault.Controllers
{

    public class FaultController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<ApplicationUser> _usermanager;

        public FaultController(IUnitOfWork unitOfWork, UserManager<ApplicationUser> usermanager)
        {
            _unitOfWork = unitOfWork;
            _usermanager = usermanager;
        }
        [Authorize(Roles = $"{SD.Role_Super_Admin},{SD.Role_Intern},{SD.Role_Admin},{SD.Role_Student_Assistant}")]
        public IActionResult GetAllFault(string search,int ? pageNumber)
        {
            pageNumber = pageNumber ?? 1;
            int pageSize = 10;
            var username = _usermanager.GetUserName(User);

            var user = _unitOfWork.User.Get(x => x.UserName == username);
            var faults = _unitOfWork.Fault.GetAll(includeProperties: "Computer").OrderBy(u => u.Computer.CreatedDate);

            foreach (var f in faults)
            {
                f.Computer.Lab = _unitOfWork.Lab.Get(o => o.Id == f.Computer.LabId);
                f.Computer.Lab.Building = _unitOfWork.Building.Get(u => u.BuildingId == f.Computer.Lab.BuildingId);
            }
            if (search != null)
            {
                var list = faults.Where(u => u.Computer.Lab.Building.CampusId == user.CampusId&& u.Id==search.Trim());

                SearchFaultVM vM = new()
                {
                    ReportedFault = PaginatedList<Fault>.Create(list.AsQueryable(), pageNumber ?? 1, pageSize)
                };

                return View(vM);
            }
            else
            {
                var list = faults.Where(u => u.Computer.Lab.Building.CampusId == user.CampusId);

                SearchFaultVM vM = new()
                {
                    ReportedFault = PaginatedList<Fault>.Create(list.AsQueryable(), pageNumber ?? 1, pageSize)
                };

                return View(vM);
            }

           
        }
        [HttpGet]
        [Authorize(Roles =SD.Role_Student_Assistant)]
        public IActionResult ReportFault(string id)
        {
            var username = _usermanager.GetUserName(User);
            var computerFromDb = _unitOfWork.Computer.Get(u => u.Id == id, includeProperties: "Lab");
            Fault fault = new();
            fault.computerId = computerFromDb.Id;
            fault.Computer = computerFromDb;
            fault.StudentEmail = username!;

            bool faultExist = _unitOfWork.Fault.Any(u => u.computerId == fault.computerId);

            if (!faultExist)
            {
                return View(fault);
            }
            else
            {
                TempData["error"] = "Fault already reported.";
                return RedirectToAction("Index", "Building");
            }

        }
        [HttpPost]
        [Authorize(Roles =SD.Role_Student_Assistant)]
        [ValidateAntiForgeryToken]
        public IActionResult ReportFault(Fault fault)
        {
            if (fault != null)
            {
                fault.Id = Guid.NewGuid().ToString();
                fault.FaultDescription= fault.FaultDescription.ToUpper();
                _unitOfWork.Fault.Add(fault);
                var computer = _unitOfWork.Computer.Get(u => u.Id == fault.computerId, includeProperties: "Lab,Computer_Comps");
                computer.ComputerComponentStatus = SD.StatusFaulty;
                _unitOfWork.Computer.Update(computer);
                _unitOfWork.Save();
                return RedirectToAction("Index", "Building");
            }
            else
            {
                TempData["error"] = "Something went wrong";
                return RedirectToAction("Index", "Building");
            }
           
        }

        [HttpGet]
        [Authorize(Roles = SD.Role_Intern)]
        public IActionResult UpdateComputerStatus(string id)
        {
            var computer = _unitOfWork.Computer.Get(u => u.Id == id, includeProperties: "Lab,Computer_Comps");
            return View(computer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles =SD.Role_Intern)]
        public IActionResult UpdateComputerStatus(Computer computer)
        {
            var username = _usermanager.GetUserName(User);

            var computerFromDb = _unitOfWork.Computer.Get(u => u.Id == computer.Id, includeProperties: "Lab,Computer_Comps");
            computerFromDb.ComputerComponentStatus = computer.ComputerComponentStatus;
            var computerFault = _unitOfWork.Fault.Get(u => u.computerId == computerFromDb.Id);
            computerFault.InternEmail = username;
            computerFault.DateUpdate = DateTime.Now;
            _unitOfWork.Computer.Update(computerFromDb);
            var p = _unitOfWork.Assign.GetAll(u => u.FaultId == computerFault.Id);
            if (computerFromDb.ComputerComponentStatus == SD.StatusHealty)
            {
                if(p!=null)
                foreach(var i in p)
                {
                        _unitOfWork.Assign.Remove(i);
                }
               
               
                _unitOfWork.Fault.Remove(computerFault);
               
            }


            _unitOfWork.Save();
            return RedirectToAction(nameof(GetAllFault));
        }

        [HttpGet]
        
        public IActionResult Details(string id)
        {
            var computer = _unitOfWork.Fault.Get(u => u.Id == id, includeProperties: "Computer");
            computer.Computer.Lab = _unitOfWork.Lab.Get(u => u.Id == computer.Computer.LabId);
            computer.Computer.Lab.Building = _unitOfWork.Building.Get(u => u.BuildingId == computer.Computer.Lab.BuildingId);
            computer.Computer.Lab.Building.Campus= _unitOfWork.Campus.Get(u=>u.CampusId==computer.Computer.Lab.Building.CampusId);
            computer.Computer.Computer_Comps = _unitOfWork.Computer_Comp.GetAll(u => u.ComputerId == computer.computerId);
            return View(computer);
        }
        [HttpGet]
        [Authorize(Roles = $"{SD.Role_Super_Admin},{SD.Role_Admin}")]
        public IActionResult AssignJobToIntern(string id)
        {
            var username = _usermanager.GetUserName(User);
            var currentUser = _unitOfWork.User.Get(u => u.Email == username);
            AssignJob job = new()
            {
                FaultId = id,
                Fault = _unitOfWork.Fault.Get(u => u.Id == id, includeProperties: "Computer"),
            };
            
            job.Fault.Computer = _unitOfWork.Computer.Get(o => o.Id == job.Fault.computerId, includeProperties: "Lab,Computer_Comps");
            job.Fault.Computer.Lab=_unitOfWork.Lab.Get(u=>u.Id==job.Fault.Computer.LabId, includeProperties: "Building");
            job.Fault.Computer.Lab.Building.Campus = _unitOfWork.Campus.Get(i => i.CampusId == currentUser.CampusId);
            AssignVM vM = new()
            {
              FaultAssign=job,
                EmployeeList = _unitOfWork.User.GetAll(u => u.Role == SD.Role_Intern && u.CampusId == currentUser.CampusId).Select(u => new SelectListItem
                {
                    Text = u.Name + "\t" + u.Usersurname,
                    Value = u.Id,
                })
            };

         
            return View(vM);
        }
        [HttpPost]
        [Authorize(Roles = $"{SD.Role_Super_Admin},{SD.Role_Admin}")]
        [ValidateAntiForgeryToken]
        public IActionResult AssignJobToIntern(AssignVM vM)
        {
          
            if(ModelState.IsValid)
            {
                bool IntenAssigned = _unitOfWork.Assign.Any(u => u.FaultId == vM.FaultAssign.FaultId && u.InternId == vM.FaultAssign.InternId);
                int InterAssigment = _unitOfWork.Assign.GetAll(u =>u.InternId == vM.FaultAssign.InternId).Count();
                if (!IntenAssigned )
                {
                    if( InterAssigment <= 2 )
                    {
                        vM.FaultAssign.Id = Guid.NewGuid().ToString();
                        _unitOfWork.Assign.Add(vM.FaultAssign);
                        _unitOfWork.Save();
                        return RedirectToAction("Index", "Building");
                    }else
                    {
                        TempData["error"] = "Oops Sorry! Intern unavailable";
                        return RedirectToAction("Index", "Building");
                    }
                  
                }
                else
                {
                    TempData["error"] = "Intern is already assigned to this fault.";
                    return RedirectToAction("Index", "Building");
                }
              
            }
            
            return View(vM);
        }
        [HttpGet]
        public IActionResult Jobs()
        {
            var username = _usermanager.GetUserName(User);
            var currentUser = _unitOfWork.User.Get(u => u.Email == username);
            if(currentUser.Role==SD.Role_Intern)
            {
                var jobs = _unitOfWork.Assign.GetAll(u=>u.InternId==currentUser.Id,includeProperties: "Fault,Intern");
                foreach (var job in jobs)
                {
                    job.Fault.Computer = _unitOfWork.Computer.Get(u => u.Id == job.Fault.computerId);
                    job.Fault.Computer.Lab = _unitOfWork.Lab.Get(u => u.Id == job.Fault.Computer.LabId);
                    job.Fault.Computer.Lab.Building = _unitOfWork.Building.Get(o => o.BuildingId == job.Fault.Computer.Lab.BuildingId);
                }
                return View(jobs);
            }
            else
            {
                var jobs = _unitOfWork.Assign.GetAll(includeProperties: "Fault,Intern");

Views/Shared/_AdminLayout.cshtml
@using Microsoft.AspNetCore.Identity
@using Report_a_Fault.Interface
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@inject IUnitOfWork _unitOfWork;

@{
    Layout = null;

    var p = _unitOfWork.Assign.GetAll(u => u.Intern.UserName == @UserManager.GetUserName(User),includeProperties:"Intern");
    var username = UserManager.GetUserName(User);
    var user = _unitOfWork.User.Get(x => x.UserName == username);
    var a = _unitOfWork.Fault.GetAll(includeProperties: "Computer");
    foreach(var i in a)
    {
        i.Computer.Lab = _unitOfWork.Lab.Get(u => u.Id == i.Computer.LabId);
        i.Computer.Lab.Building = _unitOfWork.Building.Get(u => u.BuildingId == i.Computer.Lab.BuildingId);
        i.Computer.Lab.Building.Campus = _unitOfWork.Campus.Get(u => u.CampusId == i.Computer.Lab.Building.CampusId);
    }
    var t = a.Where(u => u.Computer.Lab.Building.CampusId == user.CampusId);
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="apple-touch-icon" sizes="180x180" href="~/favicon_package_v0.16/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/favicon_package_v0.16/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/favicon_package_v0.16/favicon-16x16.png">
    <link rel="manifest" href="~/favicon_package_v0.16/site.webmanifest">
    <link rel="mask-icon" href="~/favicon_package_v0.16/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <title>_AdminLayout</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="~/Upgrading.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/styles.css" />
@*     <link rel="stylesheet" href="~/css/queries.css" /> *@
    <link rel="stylesheet" href="~/css/fundanathi.css">
    <link rel="stylesheet" href="~/css/admin.css">
</head>
<body>
    <div class="dashboard">
        <nav class="admin-nav">
            <img src="~/images/13566304-3aba-4fd1-823b-0b7edbdeee44.png" height="200px" width="300px" />
            <div class="scrollable-list">
                <ul class="main-admin-nav-list">
                    <li class="main-admin-nav-link">
                        <ion-icon class="admin-icon" name="laptop-outline"></ion-icon>
                        <a asp-action="Index" onclick="show()" asp-controller="Building">Computer Management</a>
                    </li>
                    <hr />
                    @if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Super_Admin) || User.IsInRole(SD.Role_Intern) || User.IsInRole(SD.Role_Student_Assistant))
                    {
                        <li class="main-admin-nav-link">
                            <ion-icon class="admin-icon" name="document-outline"></ion-icon>
                            <a asp-controller="Fault" onclick="show()" asp-action="GetAllFault">Reported Fault</a>
                            <div class="ann-count">@t.Count()</div>
                        </li>
                        <hr />
                    }
                  
                    @if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Super_Admin))
                    {
                        <li class="main-admin-nav-link">
                            <ion-icon class="admin-icon" name="server-outline"></ion-icon>
                            <a asp-controller="Fault" onclick="show()" asp-action="Jobs">Jobs Assignment</a>

                        </li>
                        <hr />
                        <li class="main-admin-nav-link">
                            <ion-icon class="admin-icon" name="person-add-outline"></ion-icon>
                            <a asp-controller="Account" onclick="show()" asp-action="AddUser">Add Employee</a>
                        </li>
                        <hr />
                        <li class="main-admin-nav-link">
                            <ion-icon class="admin-icon" name="people-outline"></ion-icon>
                            <a asp-controller="Account" onclick="show()" asp-action="GetAllEmployees">Employees</a>
                        </li>
                        <hr />
                        <li class="main-admin-nav-link">
                            <ion-icon class="admin-icon" name="home-outline"></ion-icon>
                            <a asp-controller="Campus" onclick="show()" asp-action="Index">Campuses</a>
                        </li>
                        <hr />
                        <li class="main-admin-nav-link">
                            <ion-icon class="admin-icon" name="list-outline"></ion-icon>
                            <a asp-controller="Department" onclick="show()" asp-action="Index">Departments</a>
                        </li>
                        <hr />
                    }
                        <li class="main-admin-nav-link">
                            <ion-icon class="admin-icon" name="key-outline"></ion-icon>
                            <a asp-controller="Account" onclick="show()" asp-action="ForgotPassword">Change Password</a>
                        </li>
                        <hr />
                    @if (User.IsInRole(SD.Role_Intern))
                    {
                        <li class="main-admin-nav-link">
                            <ion-icon class="admin-icon" name="server-outline"></ion-icon>
                            <a asp-controller="Fault" onclick="show()" asp-action="Jobs">Jobs Assignment</a>
                            <div class="ann-count">@p.Count()</div>
                        </li>
                        <hr />
                    }


                    <li class="main-admin-nav-link">
                        <a class="icon-logout" asp-controller="Account" asp-action="Logout"><ion-icon name="log-out-outline"></ion-icon></a>
                    </li>

                </ul>
           </div>
           
        </nav>
        <div class="main-content">
            @RenderBody()
        </div>

        <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
        <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
        <script src="https://jsuites.net/v4/jsuites.js"></script>
        <link rel="stylesheet" href="https://jsuites.net/v4/jsuites.css" type="text/css" />
        @if (@TempData["Success"] != null)
        {
            <script>


                jSuites.notification({
                    name: 'Notification',
                    message: '@TempData["Success"]',
                });

            </script>
        }
        @if (TempData["Error"] != null)
        {
            <script>
                jSuites.notification({
                    error: 1,
                    name: 'Error message',
                    message: '@TempData["error"]',
                });
            </script>
        }
        <script>
            var show = function () {
                // Show the loading spin
                jSuites.loading.show();
                // Hide the loading spin after two seconds
                setTimeout(function () {
                    // Hide
                    jSuites.loading.hide();
                }, 2000);
            }
        </script>
        <script>
            $(document).ready(function () {
                $('.toggle').change(function () {
                    var id = $(this).closest('tr').find('[name="Id"]').val();
                    var updatedEnabled = $(this).prop('checked');

                    $.ajax({
                        type: 'POST',
                        url: '/Account/UpdateEnabled', // Adjust the URL to your controller/action
                        data: { id: id, updatedEnabled: updatedEnabled },
                        success: function () {
                            // Optional: Handle success if needed
                        },
                        error: function (xhr, status, error) {
                            // Optional: Handle error if needed
                            console.error(xhr.responseText);
                        }
                    });
                });
            });
        </script>
        @await RenderSectionAsync("Scripts", required: false)
    </div>

</body>
</html>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@{
    var consentFeature = Context.Features.Get<ITrackingConsentFeature>();
    var showBanner = !consentFeature?.CanTrack ?? false;
    var cookieString = consentFeature?.CreateConsentCookie();
}
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta name="description" content="Central University of Technology, Fault Reporting System">
    <meta name="keywords" content="cut fault reports,fault reporting">
    <meta name="author" content="S Sithole , VV Zumani">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Report_a_Fault</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Report_a_Fault.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/sihle.css">
</head>
<body>
  
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

 
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>