Models/Labs.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Report_a_Fault.Models
{
    public class Labs
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Display(Name = "Lab Number")]
        public string Id { get; set; }
        public string LabNumber { get; set; }
        [ForeignKey("Campus")]
        public string BuildingId { get; set; }
        [ValidateNever]
        public Building Building { get; set; }
        

    }
}

Controllers/ComputerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Report_a_Fault.Interface;
using Report_a_Fault.Models;
using Report_a_Fault.ViewModel;

namespace Report_a_Fault.Controllers
{

    public class ComputerController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<ApplicationUser> _usermanager;

        public ComputerController(IUnitOfWork unitOfWork, UserManager<ApplicationUser> usermanager)
        {
            _unitOfWork = unitOfWork;
            _usermanager = usermanager;
        }
        [Authorize(Roles = $"{SD.Role_Admin},{SD.Role_Super_Admin},{SD.Role_Intern},{SD.Role_Student_Assistant}")]
        public IActionResult Index(string id,string search,int? pageNumber)
        {
            pageNumber = pageNumber ?? 1;
            int pageSize = 10;
            var computers = _unitOfWork.Computer.GetAll(u =>u.Lab.Id == id, includeProperties: "Lab,Computer_Comps").OrderBy(u => u.CreatedDate);
            foreach (var computer in computers)
            {
                computer.Lab = _unitOfWork.Lab.Get(u => u.Id == computer.LabId);
            }
            if(search != null)
            {
                SearchComputerVM vM = new()
                {
                    Computers = PaginatedList<Computer>.Create(computers.AsQueryable().Where(u => u.ComputerNumber == search.Trim()).OrderBy(u => u.ComputerNumber), pageNumber ?? 1, pageSize),
                    LabIdentityNumber = id,
                };
                return View(vM);
            }
            else
            {
                SearchComputerVM vM = new()
                {
                    Computers = PaginatedList<Computer>.Create(computers.AsQueryable().OrderBy(i=>i.ComputerNumber), pageNumber ?? 1, pageSize),
                    LabIdentityNumber = id,
                };
                return View(vM);
            }
            

        }
        [HttpGet]
        [Authorize(Roles = SD.Role_Intern)]
        public IActionResult Create(string id)
        {

           
            ComputerVM computerVM = new()
            {
                BuildingList = _unitOfWork.Lab.GetAll(u => u.Id == id).OrderBy(u => u.LabNumber).Select(u => new SelectListItem
                {
                    Text = u.LabNumber.ToString(),
                    Value = u.Id,
                })
            };

            return View(computerVM);
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Intern)]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ComputerVM computerVM)
        {
            computerVM.Computer.Id = Guid.NewGuid().ToString();
            bool computerNumberExists = _unitOfWork.Computer.Any(u => u.ComputerNumber == computerVM.Computer.ComputerNumber && u.LabId == computerVM.Computer.LabId);
            ModelState.Remove("Id");
            if (ModelState.IsValid && !computerNumberExists)
            {
                _unitOfWork.Computer.Add(computerVM.Computer);
                _unitOfWork.Save();
            }

            var lab = _unitOfWork.Lab.Get(u => u.Id == computerVM.Computer.LabId);
            string labId = lab.Id;
            return RedirectToAction("Index", new { id = labId });
        }
        [HttpGet]
        [Authorize(Roles = $"{SD.Role_Admin},{SD.Role_Super_Admin},{SD.Role_Intern},{SD.Role_Student_Assistant}")]
        public IActionResult Details(string id)
        {
            var computer = _unitOfWork.Computer.Get(u => u.Id == id, includeProperties: "Lab,Computer_Comps");
            computer.Lab.Building = _unitOfWork.Building.Get(u => u.BuildingId == computer.Lab.BuildingId);
            return View(computer);
        }
        [HttpGet]
        [Authorize(Roles =SD.Role_Intern)]
        public IActionResult Delete(string id)
        {
            var computer = _unitOfWork.Computer.Get(u => u.Id == id, includeProperties: "Lab,Computer_Comps");
            computer.Lab.Building=_unitOfWork.Building.Get(u=>u.BuildingId == computer.Lab.BuildingId);
            computer.Lab.Building.Campus = _unitOfWork.Campus.Get(u => u.CampusId == computer.Lab.Building.CampusId);
            return View(computer);
        }
        [HttpPost]
        [Authorize(Roles = SD.Role_Intern)]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Computer computer)
        {
            var computerFromDb = _unitOfWork.Computer.Get(u => u.Id == computer.Id, includeProperties: "Lab,Computer_Comps");
            _unitOfWork.Computer.Remove(computerFromDb);
            _unitOfWork.Save();
            var labId = computerFromDb.LabId;
            return RedirectToAction("Index", new { id = labId });
        }
        [HttpGet]
        public IActionResult AddRange(string id)
        {
            AddComputerRangeVM computerVM = new()
            {
                BuildingList = _unitOfWork.Lab.GetAll(u => u.Id == id).OrderBy(u => u.LabNumber).Select(u => new SelectListItem
                {
                    Text = u.LabNumber.ToString(),
                    Value = u.Id,
                })
            };
            return View(computerVM);
        }
        [HttpPost]
        public IActionResult AddRange(string labId, int numberOfComputer)
        {
            for (int i = 1; i <= numberOfComputer; i++)
            {
                if (i < 10)
                {
                    Computer computer = new()
                    {
                        Id = Guid.NewGuid().ToString(),
                        LabId = labId,
                        ComputerNumber = "0"+i.ToString(),
                    };
                    bool computerExist = _unitOfWork.Computer.Any(u => u.ComputerNumber == computer.ComputerNumber && u.LabId == computer.LabId);
                    if (!computerExist)
                    {
                        _unitOfWork.Computer.Add(computer);
                    }
                }
                else
                {
                    Computer computer = new()
                    {
                        Id = Guid.NewGuid().ToString(),
                        LabId = labId,
                        ComputerNumber = i.ToString(),
                    };
                    bool computerExist = _unitOfWork.Computer.Any(u=>u.ComputerNumber==computer.ComputerNumber&&u.LabId==computer.LabId);
                    if (!computerExist)
                    {
                        _unitOfWork.Computer.Add(computer);
                    }
                  
                }
             
                
            }
            _unitOfWork.Save();
            return RedirectToAction("Index", new { id = labId });
            
        }
    }
}

Controllers/LabController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Report_a_Fault.Interface;
using Report_a_Fault.Models;
using Report_a_Fault.ViewModel;

namespace Report_a_Fault.Controllers
{

    public class LabController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<ApplicationUser> _usermanager;
        public LabController(IUnitOfWork unitOfWork, UserManager<ApplicationUser> usermanager)
        {
            _unitOfWork = unitOfWork;
            _usermanager = usermanager;
        }
        [Authorize(Roles = $"{SD.Role_Admin},{SD.Role_Super_Admin},{SD.Role_Intern},{SD.Role_Student_Assistant}")]
        public IActionResult Index(string buildingId,string search)
        {
            var labs = _unitOfWork.Lab.GetAll(c => c.BuildingId == buildingId, includeProperties: "Building").OrderBy(u => u.LabNumber);
            if(search != null)
            {
                SearchLabVM vM = new()
                {
                    AllBuildingLabs = labs.Where(u=>u.LabNumber==search),
                    labNumber = buildingId
                };
                return View(vM);
            }
            else
            {
                SearchLabVM vM = new()
                {
                    AllBuildingLabs = labs,
                    labNumber = buildingId
                };
                return View(vM);
            }
            
        }
        [HttpGet]
        public IActionResult create(string buildingId)
        {
            var username = _usermanager.GetUserName(User);
            var user = _unitOfWork.User.Get(x => x.UserName == username);

            Labs labs = new()
            {
                BuildingId = buildingId,
            };
            return View(labs);
        }
        [HttpPost]
       
        public IActionResult create(Labs lab)
        {
            bool labExist = _unitOfWork.Lab.Any(u => u.LabNumber == lab.LabNumber && u.BuildingId == lab.BuildingId);
            if (!labExist)
            {
                ModelState.Remove("Id");
                if (ModelState.IsValid)
                {
                    lab.Id = Guid.NewGuid().ToString();
                    _unitOfWork.Lab.Add(lab);
                    _unitOfWork.Save();
                }
            }
            
         


            return RedirectToAction(nameof(Index), new { buildingId = lab.BuildingId });
        }
        //[HttpGet]
        //[Authorize(Roles = SD.Role_Intern)]
        //public IActionResult Edit(string id)
        //{
        //    var lab = _unitOfWork.Lab.Get(u => u.Id == id);
        //    return View(lab);
        //}
        //[HttpPost]
        //[Authorize(Roles = SD.Role_Intern)]
        //public IActionResult Edit(Labs lab)
        //{
        //    _unitOfWork.Lab.Update(lab);
        //    _unitOfWork.Save();
        //    return RedirectToAction(nameof(Index));

        //}
        [HttpGet]
        [Authorize(Roles = SD.Role_Intern)]

        public IActionResult Delete(string id)
        {
            var lab = _unitOfWork.Lab.Get(u => u.Id == id,includeProperties:"Building");

            return View(lab);
        }
        [HttpPost]
        [Authorize(Roles = SD.Role_Intern)]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Labs lab)
        {
            _unitOfWork.Lab.Remove(lab);
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index), new { buildingId = lab.BuildingId });

        }
        [HttpGet]


        public IActionResult Details(string id)
        {
            var lab = _unitOfWork.Lab.Get(u => u.Id == id, includeProperties: "Building");
            lab.Building.Campus = _unitOfWork.Campus.Get(u => u.CampusId == lab.Building.CampusId);
            LabNumberOfComputer lab1 = new()
            {
                Labs = lab,
                NumberOfComputer = _unitOfWork.Computer.GetAll(u=>u.LabId== id).Count(),

            };
            return View(lab1);
        }
    }
}

Views/Lab/Delete.cshtml
@model Report_a_Fault.Models.Labs

@{
    ViewData["Title"] = "Delete";
    Layout = "_AdminLayout";
}
@for (var i = 0; i < 5; i++)
{
    <div></div>
    <br />
}
<h1 class="heading-tetiary">Delete</h1>

<h3 class="subheading">Are you sure you want to delete this?</h3>
<div>
    
    <dl class="row">
        <dt class="col-sm-8">
            BUILDING NAME
        </dt>
        <div></div>
        <br />
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Building.BuildingName)
        </dd>
        <dt class="col-sm-8">
            LABORATORY NUMBER
        </dt>
        <div></div>
        <br />
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LabNumber)
        </dd>
       
    </dl>
    <div></div>
    <br />
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="BuildingId" />
        <input type="submit" value="Delete" class="btn btn-dark" />
    </form>
   
</div>

Views/Lab/Details.cshtml
@model Report_a_Fault.ViewModel.LabNumberOfComputer

@{
    ViewData["Title"] = "Details";
    Layout = "_AdminLayout";
}

@for (var i = 0; i < 5; i++)
{
    <div></div>
    <br />
}
<h1 class="heading-tetiary">REVIEW COMPUTER LABORATORY : @Model.Labs.LabNumber</h1>

<div>
    
    <hr />
    <dl class="row">
        <dt class="col-sm-8">
           CAMPUS NAME
        </dt>
        <div></div>
        <br />
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Labs.Building.Campus.CampusName)
        </dd>
        <div></div>
        <br />
        <dt class="col-sm-8">
            BUILDING NAME
        </dt>
        <div></div>
        <br />
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Labs.Building.BuildingName)
        </dd>
        <div></div>
        <br />
        <dt class = "col-sm-8">
            LABORATORY NUMBER
        </dt>
        <div></div>
        <br />
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Labs.LabNumber)
        </dd>
        <div></div>
        <br />
        <dt class="col-sm-8">
            NUMBER OF COMPUTERS IN @Html.DisplayFor(model=>model.Labs.LabNumber)
        </dt>
        <div></div>
        <br />
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumberOfComputer)
        </dd>
    </dl>
</div>

Views/Lab/Index.cshtml
@model Report_a_Fault.ViewModel.SearchLabVM

@{
    ViewData["Title"] = "Index";
    Layout = "_AdminLayout";
}
@for (var i = 0; i < 5; i++)
{
    <div></div>
    <br />
}
<div class="card-shadow">
    <h1 class="heading-tetiary">Campus Computer Labs</h1>
    @if (User.IsInRole(SD.Role_Intern))
    {
        <div class="add-new-subject">

            <a asp-controller="Lab" asp-action="Create" asp-route-buildingId="@Model.labNumber" class="add-new-subject-btn">
                <div class="inner-btn">
                    <ion-icon class="icon" name="add-outline"></ion-icon>
                    <p>Add New Lab</p>
                </div>
            </a>

        </div>
    }
   
    <table class="cus-table">
        <div class="search-bar">
            <form class="search" method="post">
                <input class="search-input" asp-for="Search" placeholder="Search Lab" />
                <button type="submit" asp-action="Index" asp-controller="Lab" asp-route-search="@Model.Search" asp-route-buildingId="@Model.labNumber" class="btn-search"><ion-icon name="search-outline"></ion-icon></button>
            </form>
        </div>
        <thead>
            <tr>
                <th>
                    BUILDING NAME
                </th>
                <th>
                    LAB
                </th>
                
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.AllBuildingLabs)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Building.BuildingName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LabNumber)
                    </td>

                    <td>
                        <div class="actions">
                            <a asp-action="Index" asp-controller="Computer" asp-route-id="@item.Id">Computers</a> 
                            
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                            
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                           
                        </div>
                        
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/Lab/create.cshtml
@model Report_a_Fault.Models.Labs

@{
    ViewData["Title"] = "create";
    Layout = "_AdminLayout";
}
@for (var i = 0; i < 5; i++)
{
    <div></div>
    <br />
}
<h1 class="heading-tetiary">ADD NEW COMPUTER LAB</h1>

<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="BuildingId" hidden class="form-control" />
          
            <div class="form-group">
                <strong>
                    <label class="control-label"> LABORATORY NUMBER</label>
                </strong>
                <div></div>
                <br />
                <input asp-for="LabNumber" class="form-control" />
                <span asp-validation-for="LabNumber" class="text-danger"></span>
            </div>
            <div></div>
            <br />
            <div class="form-group">
                <input type="submit" value="ADD" class="btn btn-dark" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}